import { text } from "@sveltejs/kit";
import { appRouter } from "$lib/routers";
import { t } from "$lib/utilities/t.server";

const data = {
  title: "FNCCI-Bagmati Province E-Commerce Training",
  scheduledDate: "2024-05-11",
  scheduledTime: "ALL DAY",
  scheduledLocation: "OFFICE",
  shouldSendEmail: false,
  attendees: [
    { name: "Rishab Nepal", office: "", phoneNumber: "9861352220", role: "participant" },
    { name: "Parasar Neupane", office: "", phoneNumber: "9843622201", role: "participant" },
    { name: "Digyan Shakya", office: "", phoneNumber: "9843519459", role: "participant" },
    { name: "Nil Bahadur KC", office: " ", phoneNumber: "9855054068", role: "participant" },
    { name: "Teklal Bhusal", office: "", phoneNumber: "", role: "participant" },
    { name: "Abeneswor KaStatusrki", office: "Dhunikhel CCI", phoneNumber: "9851111769", role: "participant" },
    { name: "Ganesh Karki", office: "Hotel Geranium Garden", phoneNumber: "9851050534", role: "participant" },
    { name: "Anita Jirel", office: "Jiri CCI", phoneNumber: "9863421009", role: "participant" },
    { name: "Sushma Shrestha", office: "Sushma Handicraft", phoneNumber: "9844002371", role: "participant" },
    { name: "Pawan Karki", office: "Makawanpur CCI", phoneNumber: "9855070110", role: "participant" },
    { name: "Pratima Shrestha", office: "Poultry Firm", phoneNumber: "", role: "participant" },
    { name: "Neha Bidhuchhe", office: "NCICK", phoneNumber: "9841348155", role: "participant" },
    { name: "Sunita Laxmi Shrestha", office: "Panchkhal CCI", phoneNumber: "9841102652", role: "participant" },
    { name: "Puja Shrestha", office: "Panchkhal CCI", phoneNumber: "9841590490", role: "participant" },
    { name: "Nabin KC", office: "Ramechhap CCI", phoneNumber: "9854040199", role: "participant" },
    { name: "Keshav Prasad Ghimire", office: "Ramechhap CCI", phoneNumber: "9854040052", role: "participant" },
    { name: "Ratna Bahadur Newar", office: "Ramechhap Municipal CCI", phoneNumber: "", role: "participant" },
    { name: "Chukta Bahadur Magar", office: "", phoneNumber: "", role: "participant" },
    { name: "Sarmila Shrestha", office: "Ratnanagar CCI", phoneNumber: "", role: "participant" },
    { name: "Ishori Simkhada", office: "Ratnanagar CCI", phoneNumber: "9864843882", role: "participant" },
    { name: "Janaki Chaudhari", office: "", phoneNumber: "9845661203", role: "participant" },
    { name: "Basanta Rana Magar", office: "", phoneNumber: "9845044076", role: "participant" },
    { name: "Ramkumar Rajbhandari", office: "Sindhuli CCI", phoneNumber: "9844082032", role: "participant" },
    { name: "Kapil Kumar Shrestha", office: "Sindhuli CCI", phoneNumber: "9844042952", role: "participant" },
    { name: "Mohan Das", office: "Thahanagar CCI", phoneNumber: "9845688672", role: "participant" },
    { name: "Pashupati Gopali", office: "Chitlang Water Resort", phoneNumber: "9861775152", role: "participant" },
    { name: "Kumar Khanal", office: "Khairahani CCI", phoneNumber: "", role: "participant" },
    { name: "Binod Aryal", office: "", phoneNumber: "", role: "participant" },
    { name: "Anup Adhikari", office: "", phoneNumber: "", role: "participant" },
    { name: "Kiran Burlakoti", office: "Chitwan Dental /CCI Khairahani", phoneNumber: "9855062705", role: "participant" },
    { name: "Purna Laxmi Lohala", office: "Mahalaxmi Hastakala Udhyog", phoneNumber: "9841877189", role: "participant" },
    { name: "Hilsan Shrestha", office: "SH Kirana Store", phoneNumber: "9861546486", role: "participant" },
    { name: "Suresh Sapkota", office: "Royal Suresh Builders Pvt.Ltd", phoneNumber: "9866195771", role: "participant" },
    { name: "Niroj Kaji Shrestha", office: "Om Shivasakti Chamal Chiura Mill", phoneNumber: "9851011082", role: "participant" },
    { name: "Ishor Dangol", office: "Nuwakot CCI", phoneNumber: "9851185919", role: "participant" },
    { name: "Rajkumar Aacharya", office: "Nuwakot CCI", phoneNumber: "", role: "participant" },
    { name: "Sudarshan Rijal", office: "Dhading CCI", phoneNumber: "9841641419", role: "participant" },
    { name: "Ramchandra Shrestha", office: "Dhading CCI", phoneNumber: "9860681650", role: "participant" },
    { name: "Ishori PrasadChalise", office: "Sindhupalchok CCI", phoneNumber: "9851159770", role: "participant" },
    { name: "Kalyani Ghising", office: "Sindhupalchok CCI", phoneNumber: "9861148559", role: "participant" },
    { name: "Anju Ranjit", office: "", phoneNumber: "", role: "participant" },
    { name: "Rupa Thapa", office: "", phoneNumber: "", role: "participant" },
    { name: "Parbati Gochhen", office: "", phoneNumber: "", role: "participant" },
    { name: "Anushka Budhathoki", office: "Dolakha CCI", phoneNumber: "9864111126", role: "participant" },
    { name: "Niruta Gurung", office: "", phoneNumber: "9845825171", role: "participant" },
    { name: "Industry and Commerce Office Rasuwa", office: "", phoneNumber: "", role: "participant" },
    { name: "Pasang Wangde Lopchan", office: "", phoneNumber: "9862498648", role: "participant" },
    { name: "Industry and Commerce Office Ramechhap", office: "", phoneNumber: "", role: "participant" },
    { name: "Manika Lama", office: "", phoneNumber: "9849545560", role: "participant" },
    { name: "Nimfurba Sherpa", office: "", phoneNumber: "9854039008", role: "participant" },
    { name: "Sujata Shrestha", office: "", phoneNumber: "9865883599", role: "participant" },
    { name: "Pusparam Ghimire", office: "", phoneNumber: "9843515925", role: "participant" },
    { name: "Industry and Commerce Office Sindhuli", office: "", phoneNumber: "", role: "participant" },
    { name: "Bimala Thapa", office: "", phoneNumber: "", role: "participant" },
    { name: "Gopal Shrestha", office: "", phoneNumber: "", role: "participant" },
    { name: "Industry and Commerce Office Chitwan", office: "", phoneNumber: "", role: "participant" },
    { name: "Nil Bahadur KC", office: "", phoneNumber: "9855054068", role: "participant" },
    { name: "Surendra Karki", office: "", phoneNumber: "9855055644", role: "participant" },
    { name: "Industry and Commerce Office Sindhupalchok", office: "", phoneNumber: "", role: "participant" },
    { name: "Dipendra Ghale", office: "", phoneNumber: "9851182293", role: "participant" },
    { name: "Mahesh Dhital", office: "", phoneNumber: "9860536270", role: "participant" },
    { name: "Industry and Commerce Office Kavrepalanchok", office: "", phoneNumber: "", role: "participant" },
    { name: "Geeta Purkuti", office: "", phoneNumber: "9849172133", role: "participant" },
    { name: "Rasila Chaulagain", office: "", phoneNumber: "9803962541", role: "participant" },
    { name: "Industry and Commerce Office Lalitpur", office: "", phoneNumber: "", role: "participant" },
    { name: "Sarita Sahi Thakuri", office: "", phoneNumber: "9849157900", role: "participant" },
    { name: "Sanjit Shrestha", office: "", phoneNumber: "9841463605", role: "participant" },
    { name: "Kalpana Maharjan", office: "", phoneNumber: "9845188202", role: "participant" },
    { name: "Ritika Shrestha", office: "", phoneNumber: "9844289070", role: "participant" },
    { name: "Rupa Thapa - Bagmati", office: "Federation of Nepal Cottage & Small Industries Bagmati Province", phoneNumber: "9841483853", role: "participant" },
    { name: "Sanchamaya Tamang", office: "Federation of Nepal Cottage & Small Industries Bagmati Province", phoneNumber: "9851178508", role: "participant" },
    { name: "Chandrawati Paneru Adhikari", office: "Federation of Nepal Cottage & Small Industries Bagmati Province", phoneNumber: "9845943582", role: "participant" },
    { name: "Radhika Chaulagain", office: "Federation of Nepal Cottage & Small Industries Bagmati Province", phoneNumber: "9845107272", role: "participant" },
    { name: "Yeshodha Kumal", office: "S.M.S Media Pvt. Ltd.", phoneNumber: "", role: "participant" },
    { name: "Siju Baniya", office: "Thahanagar, Palung", phoneNumber: "9864513030", role: "participant" },
    { name: "Riya Bista", office: "Kaushabahini baluwa tatha Gitti Prashodhan", phoneNumber: "", role: "participant" },
    { name: "Kamana Adhikari", office: "Jay Prakriti Silai Tatha Prasikshyan Company", phoneNumber: "9841004651", role: "participant" },
    { name: "Bina Bartaula", office: "Hetauda Garment Udhyami Samuha", phoneNumber: "9801844917", role: "participant" },
    { name: "Mansingh Ghalan", office: "Manahari, Makawanpur", phoneNumber: "9855069714", role: "participant" },
    { name: "Devraj Karki", office: "Dandaghare Ba ko Homestay", phoneNumber: "9761613413", role: "participant" },
    { name: "Aryaman Adhikari", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Ashish Shrestha", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Bishal Baniya", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Kristina Khatiwada", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Neha Kumari Chaudhari", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Prasansa Adhikari", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Prasant Lamichhane", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Samir Paudel", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Shikha Raya", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Smarika Singh", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Sneha Thapa", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Sagar Lama", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Shikshya Mainali", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Soham Chaudhari", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Amisha Adhikari", office: "Makawanpur Multiple Campus", phoneNumber: "", role: "participant" },
    { name: "Honorable Mr. Prakash Shrestha", office: "Ministry of Industry, Commerce, Land and Administration", phoneNumber: "", role: "Minister" },
    { name: "Mr. Rajendra Kumar KC", office: "Ministry of Industry, Commerce, Land and Administration", phoneNumber: "", role: "Secretary" },
    { name: "Krishna Katuwal", office: "", phoneNumber: "", role: "EC-Member" },
    { name: "Gobinda Sigdel", office: "", phoneNumber: "", role: "Director" },
    { name: "Taranath Chaulagain", office: "", phoneNumber: "", role: "President" },
    { name: "Krishna Kumar Gupta", office: "", phoneNumber: "", role: "President" },
    { name: "Shiva Devkota", office: "", phoneNumber: "", role: "President" },
    { name: "Dil Sundar Shrestha", office: "FNCCI Bagmati Province", phoneNumber: "9851020903", role: "President" },
    { name: "Gunraj Shrestha", office: "FNCCI Bagmati Province", phoneNumber: "9855066464", role: "Vice President" },
    { name: "Durgaraj Shrestha", office: "FNCCI Bagmati Province", phoneNumber: "9851064611", role: "Vice President" },
    { name: "Kabiraj Khatri", office: "FNCCI Bagmati Province", phoneNumber: "9851197333", role: "Treasurer" },
    { name: "Jiwan Kaji Shrestha", office: "FNCCI Bagmati Province", phoneNumber: "9851191965", role: "Executive Member" },
    { name: "Shiva Prasad Manandhar", office: "FNCCI Bagmati Province", phoneNumber: "9851023514", role: "Executive Member" },
    { name: "Birendranath Bhattrai", office: "FNCCI Bagmati Province", phoneNumber: "9851008949", role: "Executive Member" },
    { name: "krishna Bhakta Shrestha", office: "FNCCI Bagmati Province", phoneNumber: "9851043099", role: "Executive Member" },
    { name: "Rajan Karki", office: "FNCCI Bagmati Province", phoneNumber: "9841274595", role: "Executive Member" },
    { name: "Sanat Thapa", office: "FNCCI Bagmati Province", phoneNumber: "9851077809", role: "Executive Member" },
    { name: "Anil Krishna Shrestha", office: "FNCCI Bagmati Province", phoneNumber: "9855055021", role: "Executive Member" },
    { name: "Premhari Mainali", office: "FNCCI Bagmati Province", phoneNumber: "9802022445", role: "Executive Member" },
    { name: "Rudra Bahadur Khatri", office: "FNCCI Bagmati Province", phoneNumber: "9841232967", role: "Executive Member" },
    { name: "Geeta Amatya", office: "FNCCI Bagmati Province", phoneNumber: "9851176783", role: "Executive Member" },
    { name: "Grouben Taujale", office: "FNCCI Bagmati Province", phoneNumber: "9851075011", role: "Executive Member" },
    { name: "Uttam Sharma Dhakal", office: "FNCCI Bagmati Province", phoneNumber: "9855067099", role: "Executive Member" },
    { name: "Basu Narayan Shrestha", office: "FNCCI Bagmati Province", phoneNumber: "9851116743", role: "Executive Member" },
    { name: "Rajya Laxmi Shakya", office: "FNCCI Bagmati Province", phoneNumber: "9851118266", role: "Executive Member" },
    { name: "Roshni Maiya Dhaubanja", office: "FNCCI Bagmati Province", phoneNumber: "9841282672", role: "Executive Member" },
    { name: "Laxmi Khanal", office: "FNCCI Bagmati Province", phoneNumber: "9841100601", role: "Executive Member" },
    { name: "Yadav Dahal", office: "FNCCI Bagmati Province", phoneNumber: "9851110439", role: "Executive Member" },
    { name: "Situ Sainju", office: "FNCCI Bagmati Province", phoneNumber: "9851145961", role: "Small & Medium Industry Committee" },
    { name: "Padam Khadka", office: "FNCCI Bagmati Province", phoneNumber: "9841453230", role: "Small & Medium Industry Committee" },
    { name: "Kabita Manandhar", office: "FNCCI Bagmati Province", phoneNumber: "9849783090", role: "Small & Medium Industry Committee" },
    { name: "Geeta Bhusal", office: "FNCCI Bagmati Province", phoneNumber: "9841443346", role: "Small & Medium Industry Committee" },
    { name: "Rajaram Silwal", office: "FNCCI Bagmati Province", phoneNumber: "9851121605", role: "Small & Medium Industry Committee" },
    { name: "Bimala Kafle", office: "FNCCI Bagmati Province", phoneNumber: "9844226910", role: "Small & Medium Industry Committee" },
    { name: "Geeta Thapa", office: "FNCCI Bagmati Province", phoneNumber: "9841372053", role: "Small & Medium Industry Committee" },
    { name: "Mahili Danuwar", office: "FNCCI Bagmati Province", phoneNumber: "9843567166", role: "Small & Medium Industry Committee" },
    { name: "Rajesh Bajracharya", office: "FNCCI Bagmati Province", phoneNumber: "9851184394", role: "Small & Medium Industry Committee" },
    { name: "Hira Bartaula", office: "FNCCI Bagmati Province", phoneNumber: "9845294239", role: "Small & Medium Industry Committee" },
    { name: "Saru Shrestha", office: "FNCCI Bagmati Province", phoneNumber: "9849406684", role: "Small & Medium Industry Committee" },
    { name: "Bibek Manandhar", office: "FNCCI Bagmati Province", phoneNumber: "9855094777", role: "Executive Director" },
    { name: "Shristee Pudasaini", office: "FNCCI Bagmati Province", phoneNumber: "9807277692", role: "Office Assistant" },
    { name: "Sushma Thapa Magar", office: "FNCCI Bagmati Province", phoneNumber: "9806815396", role: "Program Helper" },
  
  ]
};

const caller = t.createCallerFactory(appRouter);

export const GET = async () => {
  let status = "unknown";
  try {
    await caller(() => ({})).addEvent(data);
    status = "succes";
  } catch (err) {
    console.error(err);
    status = "error";
  }

  return text(status);
};
